# Devoir 5
**Raphaël Blaude - 55112200**

In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

from pymatgen.io.cif import CifParser
from pymatgen.ext.matproj import MPRester

In [2]:
mp_key = "NKfarLsNHvBTHM4FxxhUlnMjaXDHo7fy"
mp_id = "mp-22473"

In [3]:
with MPRester(mp_key) as m:
    primitive_structure = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
    conventionnelle_structure = SpacegroupAnalyzer(primitive_structure).get_conventional_standard_structure()
    symmops = SpacegroupAnalyzer(conventionnelle_structure).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Mon travail

In [4]:
plot0 = quick_view(conventionnelle_structure,"packed",conventional=True)
display(plot0)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Ci-dessus la structure conventionnelle de l'atome sans aucun élément de symétrie. Plus loin dans ce notebook, il y aura 3 éléments de symétrie définis par une matrice de rotation et un vecteur de translation. Une image accompagnera ces éléments de symétrie pour les rendre plus visuels.

Comme ce sera peu visible à cause de la strucutre de la molécule, rappelons que:

    - L'axe rouge est l'axe a
    - L'axe vert  est l'axe b
    - L'axe bleu  est l'axe C
    

## Symétrie n°1

In [5]:
# Symétrie n°1

num_atome   = 1
num_sym     = 1
op_sym      = symmops[num_sym]

print(f"L'atome étudié est le n°{num_atome} et c'est un atome de sodium (Na).\n" )
print(f"Matrice de rotation et vecteur de translation:\n\n{op_sym}\n\n")

position_debut = conventionnelle_structure.sites[num_atome].frac_coords
position_fin   = op_sym.operate(position_debut)
print(f"Position de l'atome avant la symétrie : {position_debut}")
print(f"Position de l'atome après la symétrie : {position_fin}")

plot1 = quick_view(conventionnelle_structure, "packed", conventional = True)
display(plot1)
plot1.script('draw SYMOP ' + str(num_sym + 1) + ' {atomno = ' + str(num_atome) + '}')

L'atome étudié est le n°1 et c'est un atome de sodium (Na).

Matrice de rotation et vecteur de translation:

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


Position de l'atome avant la symétrie : [0.33333333 0.66666667 0.16666667]
Position de l'atome après la symétrie : [-0.33333333 -0.66666667 -0.16666667]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

L'opération de symétrie appliquée ici est une inversion. Toutes les coordonnées sont inversées. Le déterminant de la matrice d'inversion valant -1, c'est donc une opération de symétrie de la deuxième espèce (qui inverse la chiralité.)

C'est une opération ponctuelle de symétrie car le vecteur de translation est nul et il y a bien une matrice de rotation orthogonale d'ordre 3.

## Symétrie n°2

In [6]:
# Symétrie n°2

num_atome   = 7
num_sym     = 7
op_sym      = symmops[num_sym]

print(f"L'atome étudié est le n°{num_atome} et c'est un atome d'indium (In).\n" )
print(f"Matrice de rotation et vecteur de translation:\n\n{op_sym}\n\n")

position_debut = conventionnelle_structure.sites[num_atome].frac_coords
position_fin   = op_sym.operate(position_debut)
print(f"Position de l'atome avant la symétrie : {position_debut}")
print(f"Position de l'atome après la symétrie : {position_fin}")

plot2 = quick_view(conventionnelle_structure, "packed", conventional = True)
display(plot2)
plot2.script('draw SYMOP ' + str(num_sym + 1) + ' {atomno = ' + str(num_atome) + '}')

L'atome étudié est le n°7 et c'est un atome d'indium (In).

Matrice de rotation et vecteur de translation:

Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


Position de l'atome avant la symétrie : [0.33333333 0.66666667 0.92592484]
Position de l'atome après la symétrie : [-0.66666667 -0.33333333  0.92592484]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

On remarque ici que le déterminant de la matrice de rotation vaut -1, c'est donc une opération de symétrie de deuxième espèce (qui inverse la chiralité.)
C'est une réflexion à travers un plan miroir visible en vert sur le plot.

C'est une opération ponctuelle de symétrie car le vecteur de translation est nul et il y a bien une matrice de rotation orthogonale d'ordre 3.

## Symétrie n°3

In [7]:
# Symétrie n°3

num_atome   = 8
num_sym     = 18
op_sym      = symmops[num_sym]

print(f"L'atome étudié est le n°{num_atome} et c'est un atome de sélénium (Se).\n" )
print(f"Matrice de rotation et vecteur de translation:\n\n{op_sym}\n\n")

position_debut = conventionnelle_structure.sites[num_atome].frac_coords
position_fin   = op_sym.operate(position_debut)
print(f"Position de l'atome avant la symétrie : {position_debut}")
print(f"Position de l'atome après la symétrie : {position_fin}")

plot3 = quick_view(conventionnelle_structure, "packed", conventional = True)
display(plot3)
plot3.script('draw SYMOP ' + str(num_sym + 1) + ' {atomno = ' + str(num_atome) + '}')

L'atome étudié est le n°8 et c'est un atome de sélénium (Se).

Matrice de rotation et vecteur de translation:

Rot:
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0.66666667 0.33333333 0.33333333]


Position de l'atome avant la symétrie : [0.66666667 0.33333333 0.07407516]
Position de l'atome après la symétrie : [1.         1.         0.25925817]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

On constate ici que le déterminant de la matrice de rotation vaut 1, c'est donc une opération de symétrie de première espèce (qui conserve la chiralité.)
On peut voir que la rotation vaut π. Cette rotation est suivie d'une inversion. c'est donc une rotation hélicoïdale 2-1.

C'est donc une opération de symétrie spatiale qui est bien définie par une matrice de rotation orthogonale et par un vecteur de translation non nul.